// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBZcicYZPeyJ-FQnncn7ck4PfbvMiJn8M',
    appId: '1:757836925666:web:195fd2e5b577f05bed2cbb',
    messagingSenderId: '757836925666',
    projectId: 'thesmammadali',
    authDomain: 'thesmammadali.firebaseapp.com',
    storageBucket: 'thesmammadali.appspot.com',
    measurementId: 'G-P63F7PYV41',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBVqBve_-nB6THufV_VD90R_Gz5uMA_PE',
    appId: '1:757836925666:android:1b2f47828a102db6ed2cbb',
    messagingSenderId: '757836925666',
    projectId: 'thesmammadali',
    storageBucket: 'thesmammadali.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHtm8LXlpSX6e7334ycmi2xU975l-eOrc',
    appId: '1:757836925666:ios:9ca0111dd6541676ed2cbb',
    messagingSenderId: '757836925666',
    projectId: 'thesmammadali',
    storageBucket: 'thesmammadali.appspot.com',
    iosClientId: '757836925666-5nt60kngbd7pqmpm8cfsiv3m2tatra6c.apps.googleusercontent.com',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHtm8LXlpSX6e7334ycmi2xU975l-eOrc',
    appId: '1:757836925666:ios:9ca0111dd6541676ed2cbb',
    messagingSenderId: '757836925666',
    projectId: 'thesmammadali',
    storageBucket: 'thesmammadali.appspot.com',
    iosClientId: '757836925666-5nt60kngbd7pqmpm8cfsiv3m2tatra6c.apps.googleusercontent.com',
    iosBundleId: 'com.example.portfolio',
  );
}
